<?php

namespace Samane\Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Moral extends \Moral implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Moral' . "\0" . 'id', '' . "\0" . 'Moral' . "\0" . 'nomEmpl', '' . "\0" . 'Moral' . "\0" . 'ninea', '' . "\0" . 'Moral' . "\0" . 'rc', '' . "\0" . 'Moral' . "\0" . 'raisonSocial', '' . "\0" . 'Moral' . "\0" . 'adressEmpl', '' . "\0" . 'Moral' . "\0" . 'comptes', '' . "\0" . 'Moral' . "\0" . 'physiques'];
        }

        return ['__isInitialized__', '' . "\0" . 'Moral' . "\0" . 'id', '' . "\0" . 'Moral' . "\0" . 'nomEmpl', '' . "\0" . 'Moral' . "\0" . 'ninea', '' . "\0" . 'Moral' . "\0" . 'rc', '' . "\0" . 'Moral' . "\0" . 'raisonSocial', '' . "\0" . 'Moral' . "\0" . 'adressEmpl', '' . "\0" . 'Moral' . "\0" . 'comptes', '' . "\0" . 'Moral' . "\0" . 'physiques'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Moral $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEmpl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEmpl', []);

        return parent::getNomEmpl();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEmpl($nomEmpl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEmpl', [$nomEmpl]);

        return parent::setNomEmpl($nomEmpl);
    }

    /**
     * {@inheritDoc}
     */
    public function getNinea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNinea', []);

        return parent::getNinea();
    }

    /**
     * {@inheritDoc}
     */
    public function setNinea($ninea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNinea', [$ninea]);

        return parent::setNinea($ninea);
    }

    /**
     * {@inheritDoc}
     */
    public function getRc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRc', []);

        return parent::getRc();
    }

    /**
     * {@inheritDoc}
     */
    public function setRc($rc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRc', [$rc]);

        return parent::setRc($rc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSocial', []);

        return parent::getRaisonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSocial($raisonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSocial', [$raisonSocial]);

        return parent::setRaisonSocial($raisonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressEmpl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressEmpl', []);

        return parent::getAdressEmpl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressEmpl($adressEmpl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressEmpl', [$adressEmpl]);

        return parent::setAdressEmpl($adressEmpl);
    }

    /**
     * {@inheritDoc}
     */
    public function getComptes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComptes', []);

        return parent::getComptes();
    }

    /**
     * {@inheritDoc}
     */
    public function setComptes($comptes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComptes', [$comptes]);

        return parent::setComptes($comptes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhysiques()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhysiques', []);

        return parent::getPhysiques();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhysiques($physiques)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhysiques', [$physiques]);

        return parent::setPhysiques($physiques);
    }

}
